[build]
  base = "voicechat-frontend"
  publish = "voicechat-frontend/dist"
  command = "cd voicechat-frontend && npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
